# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2b3
sudo: false
cache: cocoapods
podfile: Example/Podfile
xcode_workspace: Example/Schwifty.xcworkspace
xcode_scheme: Scwifty-Example
xcode_sdk:
  - iphonesimulator9.1
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated xctool || brew upgrade xctool
#  - pod install --project-directory=Example
script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xctool
    -workspace Example/Schwifty.xcworkspace
    -scheme Schwifty-Example
    -sdk iphonesimulator9.1
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
    test
    ONLY_ACTIVE_ARCH=NO
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO

