# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.1
sudo: false
cache: cocoapods
podfile: Example/Podfile
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example
  - brew update
  - brew uninstall xctool
  - brew install xctool
script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xctool
    -workspace Example/Schwifty.xcworkspace
    -scheme Schwifty-Example
    -sdk iphonesimulator
    -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
    build
    test
    ONLY_ACTIVE_ARCH=NO
    CODE_SIGN_IDENTITY=""
    CODE_SIGNING_REQUIRED=NO

